GET http://localhost:5000/health

### ---------------------------- UPLOAD FEED IMAGES ----------------------------
POST http://localhost:5000/embed
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="fb_chat.json"
Content-Type: pdf

< ./data/fb_chat.json
--boundary--

### -------------------------------------------------------------------------
POST http://localhost:5000/query
Content-Type: application/json

{"query": "give me chat that was nice"}
