GET http://localhost:8000/health

### ---------------------------- UPLOAD FEED IMAGES ----------------------------
POST http://localhost:5000/embed
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="fb_chat.json"
Content-Type: pdf

< ./data/fb_chat.json
--boundary--

### -------------------------------------------------------------------------
POST http://localhost:8000/query
Content-Type: application/json

{"query": "Give me total Total Medicaid Enrollees in minnesota in the year 2024"}

### -------------------------------------------------------------------------
POST http://localhost:8000/query_ollama
Content-Type: application/json

{"query": "Give me total Total Medicaid Enrollees in kansas in the year 2024"}
